environment: "development"
address: "localhost"
port: 3000
pid: "tmp/pids/starship.pid"
maintainance:
  enabled: false
  user_sessions: true
  announcement: "The site is down for maintainance and will return soon"
